@startuml
actor Benutzer
participant Browser
participant Server
database Datenbank
Benutzer ->  Browser
  activate Browser
  Browser ->  Server
    activate Server
    Server ->  Datenbank
      activate Datenbank
    Server <-- Datenbank
    deactivate Datenbank
  Browser <-- Server
  deactivate Server
Benutzer <-- Browser
deactivate Browser
@enduml