ifndef::imagesdir[:imagesdir: ./images]
ifndef::plantUMLDir[:plantUMLDir: .plantuml/]

== Generierte Diagramme mit PlantUML

=== Aktivitätsdiagramme

Hier ein minimalistisches Aktivitätsdiagramm:

[source, plantuml]
----
[plantuml]
--
start
:activity;
--
----

[plantuml,"{plantUMLDir}activity","png"]
--
start
:activity;
--


=== Komponentendiagramme

Statische Diagramme finden wir für PlantUML weniger geeignet, weil
das automatische Layout ziemlich schnell unübersichtlich wird.
Im folgenden Beispiel haben wir durch Mischung von einfachen `->`
und doppelten `-->` Pfeilen etwas Einfluss auf das Layout genommen.

Bei Diagrammen mit mehr als 10-15 _Kästchen_ (egal ob Klassen oder Komponenten)
funktioniert das unserer Erfahrung nach nicht mehr übersichtlich,
da sind manuell erstellte Diagramme mit anderen Werkzeugen überlegen.

.Ein einfaches Komponentendiagramm
[plantuml, "{plantUMLDir}plantuml-demo", "png"]
----
skinparam componentStyle uml2

component asciidoctorj as adj
component docToolChain as dtc

file AsciiDoc as input
file html
file pdf
file confluence
file many_more


input -> adj
adj -> dtc : "html,\ndocbook"

adj --> html
adj --> pdf

dtc --> confluence
dtc --> many_more
----

.Ein Sequenzdiagramm
[plantuml,"{plantUMLDir}seq1",png]
----
actor Benutzer
Benutzer ->  Browser
  Browser ->  Server
    Server ->  Datenbank
    Server <-- Datenbank
  Browser <-- Server
Benutzer <-- Browser
----

Dazu schreiben Sie folgenden Quelltext:
----
[plantuml,"{plantUMLDir}seq1",png]
--
actor Benutzer
Benutzer ->  Browser
  Browser ->  Server
    Server ->  Datenbank
    Server <-- Datenbank
  Browser <-- Server
Benutzer <-- Browser
--
----

Dieses kann man z.B. noch mit den richtigen Element-Typen und Aktivierungen der Elemente anreichern:

.Ein Sequenzdiagramm
[plantuml,"{plantUMLDir}seq2",png]
----
actor Benutzer
participant Browser
participant Server
database Datenbank
Benutzer ->  Browser
  activate Browser
  Browser ->  Server
    activate Server
    Server ->  Datenbank
      activate Datenbank
    Server <-- Datenbank
    deactivate Datenbank
  Browser <-- Server
  deactivate Server
Benutzer <-- Browser
deactivate Browser
----

PlantUML-Diagramme können auch aus externen Dateien referenziert werden:

[plantuml,"{plantUMLDir}seq3",png]
----
include::sequences/demoSequence.puml[]
----

Mit dem Block-Macro geht es sogar noch kürzer:

plantuml::sequences/demoSequence.puml["{plantUMLDir}seq4"]
