# Gemfile to create sites with Jekyll and AsciiDoc
#
#

source "https://rubygems.org"

gem "minimal-mistakes-jekyll"

group :jekyll_plugins do
  # gem 'jekyll-asciidoc'
# TODO: get asciidoctor-diagram to work in container
# gem 'asciidoctor-diagram', '~> 1.4.0'
end
