# docker-compose definition for developing the site.
#
version: '2'

services:
  arc42-jekyll:
    build: .
    image: hhgdac-jekyll/0.1
    command: jekyll serve --trace --host 0.0.0.0 --watch --incremental
    environment:
      - JEKYLL_ENV=development
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - $PWD/_config-dev.yml:/srv/jekyll/_config.yml
