# docker-compose definition for developing the site.
#
# version 0.2 tried AsciiDoc-Diagram integration
# version 0.3 removed AsciiDoc Diagram again, as it didn't work

version: '2'

services:
  hhgdac-jekyll:
    build: .
    image: hhgdac-jekyll/0.3
    command: jekyll serve --trace --host 0.0.0.0 --watch 
    environment:
      - JEKYLL_ENV=development
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - $PWD/_config-dev.yml:/srv/jekyll/_config.yml
